version: '3'

services:
  mongo:
    image: mongo
    container_name: database
    environment:
      MONGO_INITDB_DATABASE: zap
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
    
