import "@/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ReactRelayContext } from "react-relay";
import Providers from "./providers";

const bevellier = localFont({
  src: "../../public/bevellier.ttf",
  variable: "--font-bevellier",
});

const satoshi = localFont({
  src: "../../public/satoshi.ttf",
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en" className="bg-secondary-50/40">
      <body
        className={`${bevellier.variable} ${satoshi.variable} font-sans h-full`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
