import "@/styles/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Providers from "./providers";
import { cookies } from "next/headers";

const bevellier = localFont({
  src: "../../public/bevellier.ttf",
  variable: "--font-bevellier",
});

const satoshi = localFont({
  src: "../../public/satoshi.ttf",
  variable: "--font-satoshi",
});

export const metadata: Metadata = {
  title: "Zap",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  const token = cookies().get("token")?.value;

  return (
    <html lang="en" className="bg-secondary-50/40">
      <body
        className={`${bevellier.variable} ${satoshi.variable} font-sans h-full`}
      >
        <Providers token={token}>{children}</Providers>
      </body>
    </html>
  );
}
